version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1` && npx cypress run --spec "./cypress/e2e/test-group-1/*.js"
      - cypress/run:
          cypress-command: export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1` && npx cypress run --spec "./cypress/e2e/test-group-2/*.js"