name: Cypress Tests

on: push

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  cypress-job-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:cypress:parallel:1
  cypress-job-2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:cypress:parallel:2
  close_batch:
    needs: [cypress-job-1, cypress-job-2]
    # Ensure we close the batch even if our tests fail
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status 
        uses: wei/curl@v1.1.1
        with:
          args: -v -X DELETE https://eyesapi.applitools.com/api/sessions/batches/${{ env.APPLITOOLS_BATCH_ID }}/close/bypointerid?apiKey=${{ secrets.APPLITOOLS_API_KEY }}