name: Cypress Tests

on: push

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx cypress run